name: abide
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 1.0
val_set: 0.0
path: /neuro/labs/grantlab/users/arafat.hussain/Data/ABIDE_pcp/abide_absolute_residual_scores.npy
stratified: False
drop_last: True
