wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.8
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721165250.630485
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.6.8
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
